CREATE TABLE Users (
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    streak INT DEFAULT 1,
    user_log TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_pic VARCHAR(255),
    tasks JSON
);

CREATE TABLE Tasks (
  task_id INT PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(500) NOT NULL,
  start_time DATETIME,
  end_time DATETIME,
  length INT,
  repeated BOOLEAN DEFAULT FALSE,
  category VARCHAR(100)
);